### ISSUE TITLE
🎮 PSP guide (PPSSPP)

### ISSUE THREAD

**Issue by nchristopher** [nchristopher/steamdeck-emulation#14]

**Comment by Vaarlion** [comment]
I've done it pretty much without issues, I'll make a quick guide that respect the format

**Comment by nchristopher** [comment]
If you'd like to create a guide, go ahead - you can follow the [contributing guidelines](https://github.com/nchristopher/steamdeck-emulation/blob/main/CONTRIBUTING.md) to get a rough idea on how the guide should be. If not, I'll get to this eventually.
