### ISSUE TITLE
🐛 m64p - No ROMs Load

### ISSUE THREAD

**Issue by OatmealParmesan** [nchristopher/steamdeck-emulation#25]
After following the N64 guide, I cannot get any game to load, it just boots to the emulator. Looks like others on the Reddit thread are having the same issue.

![image](https://user-images.githubusercontent.com/75916739/157491608-bfe40619-0585-4534-a696-da03352a2848.png)

**Comment by nchristopher** [comment]
Hmm, could you try manually running `flatpak run io.github.m64p.m64p <path-to-rom>` (replacing `<path-to-rom>` with your game's path) in a terminal? It works for me, so I'm not sure why it isn't for some people.

**Comment by nchristopher** [comment]
What's weird about this bug is that I can load ROMs using the CLI on my Linux PC but not on Deck. I'm still investigating.

**Comment by nchristopher** [comment]
The latest version of the `m64p` flatpak seemed to introduce this issue. The bug is being tracked at https://github.com/flathub/io.github.m64p.m64p/issues/55.

In the meantime, you can run this in a terminal to downgrade `m64p` to a working version:
```bash
sudo flatpak update --commit=534c9e389049cb1ef8bd4206fbb5042c4d18be5363ae15e2ab979fd10b78f6c8 io.github.m64p.m64p
```

**Comment by OatmealParmesan** [comment]
> The latest version of the `m64p` flatpak seemed to introduce this issue. The bug is being tracked at [flathub/io.github.m64p.m64p#55](https://github.com/flathub/io.github.m64p.m64p/issues/55).
> 
> In the meantime, you can run this in a terminal to downgrade `m64p` to a working version:
> 
> ```shell
> sudo flatpak update --commit=534c9e389049cb1ef8bd4206fbb5042c4d18be5363ae15e2ab979fd10b78f6c8 io.github.m64p.m64p
> ```

Thanks for your help! Hopefully future updates address for flatpack.

![image](https://user-images.githubusercontent.com/75916739/157689619-0e320c1f-b270-4d4c-a122-e028cb5d97b9.png)

**Comment by nchristopher** [comment]
A more permanent fix, which should work with the latest version, is giving the Flatpak access to your ROMs folder.

```bash
flatpak override --filesystem=<roms directory>:ro io.github.m64p.m64p
```

I'll add this to the guide soon.

**Comment by nchristopher** [comment]
The `m64p` Flatpak has been fixed - go ahead and update it from Discover.

**Comment by soxhi8** [comment]
Still not fixed in latest version from Discover, build date Mar 15 2022. m64p still needs `--filesystem=host:ro` to load any ROM via CLI.
