### ISSUE TITLE
m64p - White screen when exiting game within Steam Deck GUI

### ISSUE THREAD

**Issue by RichOnPeers** [nchristopher/steamdeck-emulation#31]
White screen when exiting a game.
Similar to https://github.com/nchristopher/steamdeck-emulation/issues/25 but when exiting with the Steam Deck GUI.

![P_20220315_132214_1](https://user-images.githubusercontent.com/2156658/158377210-1e269e99-792a-4eb6-a20f-c5916dd5c96a.jpg)

**Comment by nchristopher** [comment]
This seems normal, you're exiting the game within the emulator, but not exiting the game itself. Could you clarify what the actual bug is?

**Comment by RichOnPeers** [comment]
When I use the Deck UI and choose "Quit Game" the emulated game closes but the emulator does not shut down (white screen) and the Deck UI can not terminate the process. Leaving it running with the Deck UI showing "Exiting game..." forever.

**Comment by RichOnPeers** [comment]
Here's how it looks.
![2022-03-16 21 01 45-1](https://user-images.githubusercontent.com/2156658/158680586-86acdb26-58cb-461d-a769-062a6304d6a3.jpg)

**Comment by nchristopher** [comment]
How did you solve this issue?

**Comment by aveneyer** [comment]
This has been part of m64p for a while. Usually, people would use AHK or something similar to create exit scripts if they wanted to close m64p on shutdown.

For Steam Deck, here are my suggestions for now.
- Press and Hold the Steam key. While holding it down, use the right trackpad. This allows you to use the mouse, even in Steam mode, to choose File + Exit.
In Controller settings, map a key to toggle Fullscreen
- Map a Key to "Alt Key" (note: must be Left-Alt) with a sub-command of "Enter Key" - This matches the "ALT + RETURN" hotkey to switch between Fullscreen in m64p. You can then exit directly from emulation if you choose.

**Comment by nchristopher** [comment]
As this is an m64p issue, not one with the guide itself, I'm closing this.
