### ISSUE TITLE
Dolphin - Unable to set game path

### ISSUE THREAD

**Issue by RichOnPeers** [nchristopher/steamdeck-emulation#32]
The directory appears empty in Dolphin and clicking "open" does nothing. 

The folder is on the internal drive and I have run this command to give access:
`flatpak override org.DolphinEmu.dolphin-emu --filesystem=/home/deck/roms/ --user` 

![P_20220315_134332](https://user-images.githubusercontent.com/2156658/158383730-3b018111-4c7b-47cb-a2f8-04251797de82.jpg)

**Comment by nchristopher** [comment]
Are you able to manually enter in the path instead of using the directory picker?

**Comment by RichOnPeers** [comment]
Didn't work, but got to it to work by long pressing the folder to highlight the folder name and then clicking Open instead of trying to open it from within.

Issue can be closed.
