### ISSUE TITLE
🎮 Nintendo 64 guide (simple64)

### ISSUE THREAD

**Issue by nchristopher** [nchristopher/steamdeck-emulation#4]
There are multiple N64 emulators, each with their pros and cons. Multiple guides might be necessary.

**Comment by darsor** [comment]
It looks like the N65 guide is out of saye. The m64p flatpack was renamed to simple64.

**Comment by nchristopher** [comment]
Fixed by c6c552adf904bbedf8b006253877873ea9b65d3c.
